### ISSUE TITLE
Add a configuration option in INI file for viewing HTML code

### ISSUE THREAD

**Issue by amador-duran-toro** [Josdelsan/Proteus#26]
To facilitate the development of XSLT stylesheets, add a configuration option in the INI file for allowing the context menu in the embedded browser and therefore, being able of inspect the generated HTML code. 

Since this is an "advanced user" feature, it should be disabled by default.

**Comment by Josdelsan** [comment]
Generated HTML code can be accessed from proteus temporal files directory `.proteus` by opening `temp_project_render.html`. It is a new feature derived from the refactor of document rendering. Links to assets and other resources are resolved using absolute file paths.
