### ISSUE TITLE
PDF export does not include resources

### ISSUE THREAD

**Issue by alcarazzam** [Josdelsan/Proteus#37]
The PDF export doesn't include any resources (CSS, images, ...) with version v1.1.0-beta.

![pdf-export](https://github.com/user-attachments/assets/48d53bbf-7730-4b79-b575-dcd61ac58929)

CC @josmorcor3 @Juan-Varo

**Comment by Josdelsan** [comment]
It was a problem related to the new method of generating HTML. The PDF export fix will be included in the v1.1.1-beta release in a few days.In the meantime, if you need to export a document in PDF you can export in HTML then using a webbrowser to print to PDF or switch to hotfix branch.
