### ISSUE TITLE
Figures with filename including non-English characters are not shown in HTML transformation

### ISSUE THREAD

**Issue by amador-duran-toro** [Josdelsan/Proteus#7]
Figures with filename including non-English characters are not shown in HTML transformation, independently of using disable-output-escaping="no" or disable-output-escaping="yes" in XSLT. The exported HTML is displayed correctly in Firefox, Chrome, Edge and Opera, so it seems a limitation of the PyQt embedded browser.

**Comment by Josdelsan** [comment]
The issue was URL-encoded characters not being correctly decoded in the request interceptor module.
